"""Local Stable Diffusion generation route for dog harness previews."""

from __future__ import annotations

from pathlib import Path
from typing import Any
from uuid import uuid4

from fastapi import APIRouter, File, Form, UploadFile
from fastapi.responses import JSONResponse

from app.config import STATIC_DIR, UPLOAD_DIR
from app.services.stable_diffusion_service import StableDiffusionError, generate_dog_harness_image


router = APIRouter(prefix="/preview", tags=["generation"])

ALLOWED_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp"}
def _error_response(status_code: int, stage: str, message: str) -> JSONResponse:
    return JSONResponse(
        status_code=status_code,
        content={
            "status": "failed",
            "stage": stage,
            "message": message,
        },
    )


def _safe_extension(filename: str | None, content_type: str | None) -> str:
    extension = Path(filename or "").suffix.lower()
    if extension in ALLOWED_EXTENSIONS:
        return extension
    if content_type == "image/jpeg":
        return ".jpg"
    if content_type == "image/webp":
        return ".webp"
    return ".png"


async def _save_upload(upload_file: UploadFile, prefix: str) -> Path:
    if upload_file.content_type and not upload_file.content_type.startswith("image/"):
        raise ValueError(f"{prefix} must be an image file")

    data = await upload_file.read()
    if not data:
        raise ValueError(f"{prefix} file is empty")

    UPLOAD_DIR.mkdir(parents=True, exist_ok=True)
    extension = _safe_extension(upload_file.filename, upload_file.content_type)
    destination = UPLOAD_DIR / f"{prefix}_{uuid4().hex}{extension}"
    destination.write_bytes(data)
    return destination


def _public_static_path(path: Path) -> str:
    return f"/static/{path.relative_to(STATIC_DIR).as_posix()}"


@router.post("/generate", response_model=None)
async def generate_pet_product_preview(
    dog_image: UploadFile = File(...),
    product_image: UploadFile = File(...),
    prompt: str = Form(default="a dog is wearing the harness"),
) -> Any:
    """Generate an image from one dog image, one harness image, and a prompt."""

    try:
        dog_path = await _save_upload(dog_image, "dog")
        harness_path = await _save_upload(product_image, "harness")
    except ValueError as exc:
        return _error_response(400, "validation", str(exc))

    try:
        result = generate_dog_harness_image(
            dog_image_path=dog_path,
            harness_image_path=harness_path,
            prompt=prompt,
        )
    except StableDiffusionError as exc:
        return _error_response(500, "stable_diffusion", str(exc))

    return {
        "status": "success",
        "result_image_path": _public_static_path(result.result_image_path),
        "base_image_path": _public_static_path(result.base_image_path),
        "mask_image_path": _public_static_path(result.mask_image_path),
        "mask_overlay_path": _public_static_path(result.mask_overlay_path),
        "product_reference_path": _public_static_path(result.product_reference_path),
        "prompt": result.prompt,
        "negative_prompt": result.negative_prompt,
        "backend": "diffusers-stable-diffusion-inpaint-ip-adapter",
        "message": "Generated by inpainting the dog torso while preserving the dog image outside the mask and using the harness as an IP-Adapter reference.",
    }
